version: 2.1

workflows:
  version: 2
  default:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
    #   - lint:
    #       requires:
    #         - prepare
    #       filters:
    #         tags:
    #           only: /.*/
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/

defaults: &defaults
  docker:
    - image: cimg/node:14.17
  working_directory: ~/mapbox-gl-rtl-text

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - persist_to_workspace:
          root: ~/
          paths:
            - mapbox-gl-rtl-text
            - .ssh
#   lint:
#     <<: *defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - restore_cache:
#           keys:
#             - v2-lint-{{ .Branch }}
#             - v2-lint
#       - run: npm run lint
#       - save_cache:
#           key: v2-lint-{{ .Branch }}-{{ .Revision }}
#           paths:
#             - '.eslintcache'

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: ./build.sh
      - store_artifacts:
          path: "build"
      - persist_to_workspace:
          root: ~/
          paths:
            - mapbox-gl-rtl-text/build
            - mapbox-gl-rtl-text/mapbox-gl-rtl-text.js
            - mapbox-gl-rtl-text/mapbox-gl-rtl-text.min.js
            - mapbox-gl-rtl-text/mapbox-gl-rtl-text.wasm.js
            - mapbox-gl-rtl-text/mapbox-gl-rtl-text.wasm.min.js

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm test